# Generated by Django 4.0.3 on 2022-04-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', False)), fields=('created_at',), name='unique_booking_per_time'),
        ),
    ]
