# Generated by Django 4.0.3 on 2022-04-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_unique_booking_per_time'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking_per_time',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', False)), fields=('created_at', 'room'), name='unique_booking_per_time'),
        ),
    ]
