# Generated by Django 4.0.3 on 2022-04-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_booking_unique_booking_per_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='expire_at',
            field=models.DateTimeField(null=True),
        ),
    ]
