# Generated by Django 4.0.3 on 2022-04-06 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reservation_start',
            field=models.DateTimeField(null=True),
        ),
    ]
